
// LOGIN 
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const PROFILE_PENDING = 'PROFILE_PENDING';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

// LANG SWITCHER
export const LANGUAGE_CHANGE = 'LANGUAGE_CHANGE';

// REGISTER
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

//GENERATE OTP
export const GENERATE_OTP_PENDING = 'GENERATE_OTP_PENDING';
export const GENERATE_OTP_ERROR = 'GENERATE_OTP_ERROR';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const SET_REGISTER_OBJ = 'SET_REGISTER_OBJ';
export const PRELOAD_OTP = 'PRELOAD_OTP';

// VERIFY_OTP
export const VERIFY_OTP_PENDING = 'VERIFY_OTP_PENDING';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';

//Forgot/Reset Password
export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const SET_RESET_PASSWORD_OBJ = 'SET_RESET_PASSWORD_OBJ';

//Center Register Info 
export const REGISTER_INFO_PENDING = 'REGISTER_INFO_PENDING';
export const REGISTER_INFO_ERROR = 'REGISTER_INFO_ERROR';
export const REGISTER_INFO_SUCCESS = 'REGISTER_INFO_SUCCESS';
export const SET_REGISTER_INFO_OBJ = 'SET_REGISTER_INFO_OBJ';
//VERIFY EMAIL
export const EMAIL_VERIFICATION_PENDING = 'EMAIL_VERIFICATION_PENDING';
export const EMAIL_VERIFICATION_ERROR = 'EMAIL_VERIFICATION_ERROR';
export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS';
export const SET_EMAIL_VERIFICATION_OBJ = 'SET_EMAIL_VERIFICATION_OBJ';


// GET Notifications
export const GET_NOTIFICATION_PENDING = 'RESET_PASSWORD_PENDING';
export const GET_NOTIFICATION_ERROR = 'RESET_PASSWORD_ERROR';
export const GET_NOTIFICATION_SUCCESS = 'RESET_PASSWORD_SUCCESS';

// CHANGE EMAIL 
export const CHANGE_EMAIL_PENDING = 'CHANGE_EMAIL_PENDING';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR';
export const CHANGE_EMAIL_IN_PROFILEDATA = 'CHANGE_EMAIL_IN_PROFILEDATA';

// CHANGE PASSWORD 
export const CHANGE_PASSWORD_PENDING = 'CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

//ADDRESS DETAILS
export const ADDRESS_DETAILS_PENDING = 'ADDRESS_DETAILS_PENDING';
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS';
export const ADDRESS_DETAILS_ERROR = 'ADDRESS_DETAILS_ERROR';
export const ADDRESS_DETAILS_OBJ = 'ADDRESS_DETAILS_OBJ';

//REGION INFO
export const GET_CITYLIST_PENDING = 'GET_CITYLIST_PENDING';
export const GET_CITYLIST_SUCCESS = 'GET_CITYLIST_SUCCESS';
export const GET_CITYLIST_ERROR = 'GET_CITYLIST_ERROR';

//ADD CAREGIVER
export const ADD_CAREGIVER_PENDING = 'ADD_CAREGIVER_PENDING';
export const ADD_CAREGIVER_SUCCESS = 'ADD_CAREGIVER_SUCCESS';
export const ADD_CAREGIVER_ERROR = 'ADD_CAREGIVER_ERROR';
export const ADD_CAREGIVER_OBJ = 'ADD_CAREGIVER_OBJ'

//REMOVE CAREGIVER
export const REMOVE_CAREGIVER_PENDING = 'REMOVE_CAREGIVER_PENDING';
export const REMOVE_CAREGIVER_SUCCESS = 'REMOVE_CAREGIVER_SUCCESS';
export const REMOVE_CAREGIVER_ERROR = 'REMOVE_CAREGIVER_ERROR';

//VIEW CAREGIVER
export const VIEW_CAREGIVER_PENDING = 'VIEW_CAREGIVER_PENDING';
export const VIEW_CAREGIVER_SUCCESS = 'VIEW_CAREGIVER_SUCCESS';
export const VIEW_CAREGIVER_ERROR = 'VIEW_CAREGIVER_ERROR';

// PROFILE >> UPLOAD DOCUMENTS 
export const UPLOAD_DOCUMENTS_PENDING = 'UPLOAD_DOCUMENTS_PENDING';
export const UPLOAD_DOCUMENTS_SUCCESS = 'UPLOAD_DOCUMENTS_SUCCESS';
export const UPLOAD_DOCUMENTS_ERROR = 'UPLOAD_DOCUMENTS_ERROR';

// ADD AND APPLY FOR THE LICENSE.
export const ADD_APPLY_LICENSE_PENDING = 'ADD_APPLY_LICENSE_PENDING';
export const ADD_APPLY_LICENSE_SUCCESS = 'ADD_APPLY_LICENSE_SUCCESS';
export const ADD_APPLY_LICENSE_ERROR = 'ADD_APPLY_LICENSE_ERROR';

//ADD GRADES
export const ADD_GRADES_PENDING = 'ADD_GRADES_PENDING';
export const ADD_GRADES_ERROR = 'ADD_GRADES_ERROR';
export const ADD_GRADES_SUCCESS = 'ADD_GRADES_SUCCESS';
export const ADD_GRADES_OBJ = 'ADD_GRADES_OBJ';

